# Generated by Django 4.2.2 on 2023-08-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recomendaciones/'),
        ),
    ]
