# Generated by Django 4.2.2 on 2023-08-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_alter_recomendacion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
