# Generated by Django 4.2.2 on 2023-08-03 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0002_remove_userprofile_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
